**QR-алгоритм**

QR-алгоритм — это численный метод в линейной алгебре, предназначенный
для отыскания всех собственных чисел и собственных векторов матрицы.

**Алгоритм**

Исходные данные: симметричная матрица $A$ (элементы $a_{ij}$).

Вычисляемые данные: диагональная матрица $\Lambda$ (элементы
$\lambda_{ij}$).

Пусть $A$ — вещественная матрица, для которой мы хотим найти собственные
числа и векторы.

Положим $A_{0}=A$.

На $k$-м шаге (начиная с $k$ = 0) вычислим QR-разложение
$A_{k}=Q_{k}R_{k}$, где $Q_{k}$ — ортогональная матрица (то есть
$Q_{k}^{T} = Q_{k}^{-1}$), а $R_{k}$ — верхняя треугольная матрица.
Затем мы определяем $A_{k+1} = R_{k}Q_{k}$.

Заметим, что
$$A_{k+1} = R_{k}Q_{k} = Q_{k}^{-1}Q_{k}R_{k}Q_{k} = Q_{k}^{-1}A_{k}Q_{k} = Q_{k}^{T}A_{k}Q_{k},$$
то есть все матрицы $A_{k+1}$ являются подобными, и подобными матрице
$A$, то есть их собственные значения равны.

Пусть все диагональные миноры матрицы $A$ не вырождены. Тогда
последовательность матриц $A_{k}$ при $\displaystyle k \to \infty$,
сходится по форме к клеточному правому треугольному виду,
соответствующему клеткам с одинаковыми по модулю собственными
значениями.

Для того, чтобы получить собственные векторы матрицы, нужно перемножить
все матрицы $Q_{k}$.

Будем считать, что собственные числа положительно-определённой матрицы
$A$ упорядочены по убыванию:
$$\lambda_1 > \lambda_2 > \ldots > \lambda_n > 0.$$

Пусть $$\Lambda =
\left[\begin{array}{cccc} 
\lambda_1 & 0 & \ldots & 0\\
0 & \lambda_2 & \ldots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \ldots & \lambda_n
\end{array}\right]$$ а $S$ — матрица, составленная из собственных
векторов матрицы $A$. Тогда, матрица $A$ может быть записана в виде
спектрального разложения $$A = S \Lambda S^{T}.$$ Найдём выражение для
степеней исходной матрицы через матрицы $Q_{k}$ и $R_k$. С одной
стороны, по определению QR-алгоритма:
$$A^{k} = A_1^{k} = (Q_1 R_1)^{k} = Q_1(R_1 Q_1)^{k-1}R_1 = Q_1 A_2^{k-1} R_1.$$
Применяя это соотношение рекурсивно, получим:
$$A^{k} = Q_1 \cdot \ldots \cdot Q_k \cdot R_k \cdot \ldots \cdot R_1$$
Введя следующие обозначения: $$S_k = Q_1 \cdot \ldots \cdot Q_k,$$
$$T_k = R_k \cdot \ldots \cdot R_1,$$ получим $$A^{k} = S_k T_k.$$ С
другой стороны: $$A^{k} = S \Lambda^{k} S^{T}.$$ Приравнивая правые
части последних двух формул, получим: $$S \Lambda^{k} S^{T} = S_k T_k.$$
Предположим, что существует LU-разложение матрицы $S^{T}$:
$$S^{T} = LU,$$ тогда $$S \Lambda^{k} L U = S_k T_k.$$ Умножим справа на
обратную к $U$ матрицу, а затем — на обратную к $\Lambda_{k}$:
$$S \Lambda^{k} L = S_k T_k U^{-1},$$
$$S \Lambda^{k} L \Lambda^{-k} = S_k T_k U^{-1} \Lambda^{-k}.$$
Рассматривая матрицу $\Lambda^k L \Lambda^{-k}$, заметим, что
$$(\Lambda^k L \Lambda^{-k})_{ij} = \begin{cases} \ell_{ij}\left(\frac{\lambda_i}{\lambda_j}\right)^k, & i>j, \\1 & i = j,\\ 0, \text{иначе} \end{cases}$$
поэтому матрица $\Lambda^k L \Lambda^{-k} \to I$ при $k \to \infty$, где
$I$ — единичная матрица.

Тогда $$S_k T_k U^{-1} \Lambda^{-k} \to S.$$ Обозначим
$$P_k = T_k U^{-1} \Lambda^{-k},$$ причём матрица $P_k$ является
верхнетреугольной, как произведение верхнетреугольных и диагональных
матриц.

Таким образом, мы доказали, что $$S_k P_k \to S.$$ Из единственности
QR-разложения следует, что если произведение ортогональной и треугольной
матрицы сходится к ортогональной матрице, то треугольная матрица
сходится к единичной матрице. Из сказанного следует, что
$$S_k = Q_1 \cdot \ldots \cdot Q_k \to S.$$ То есть матрицы $S_k$
сходятся к матрице собственных векторов матрицы A.

Так как
$$A_{k+1} = Q_k^{T} A_k Q_k = \ldots = \left(Q_k^{T} \cdot \ldots \cdot Q_1^{T} \right) A_1 \left(Q_1 \cdot \ldots \cdot Q_k \right) = (Q_1 \cdot \ldots \cdot Q_k )^{T} A (Q_1 \cdot \ldots \cdot Q_k),$$
то $$A_{k+1} = S_k^{T} A S_k.$$ Переходя к пределу, получим:
$$\lim_{k \to \infty} A_k = \lim_{k \to \infty} A_{k+1} = S^{T} A S = S^{T} S \Lambda S^{T} S = \Lambda.$$
Итак, мы доказали, что QR-алгоритм позволяет вычислить собственные
значения и собсвенные вектора для симметричной положительно-определённой
матрицы.

In [5]:
import numpy as np

n = 4
A = 2 * np.eye(n) - np.eye(n, k=1) - np.eye(n, k=-1)

def qr_iteration(A):
    temp = np.eye(A.shape[0])
    for i in range(1000):
        Q, R = np.linalg.qr(A) 
        A = np.dot(R, Q)
        temp = np.dot(temp, Q) 
    return np.diag(A), temp.transpose()
        
eigvals, eigvecs = qr_iteration(A)
n_eigvals, n_eigvecs = np.linalg.eig(A)

print("Вещественная матрица A, для которой мы хотим найти собственные числа и векторы:")
print(A)

print("\nСобственные числа вычисленные с помощью QR алгоритма:")
print(eigvals)
print("\nСобственные числа вычисленные с помощью numpy:")
print(n_eigvals)

print("\nСобственные векторы вычисленные с помощью QR алгоритма:")
print(eigvecs)
print("\nСобственные векторы вычисленные с помощью numpy:")
print(n_eigvecs) 


Вещественная матрица A, для которой мы хотим найти собственные числа и векторы:
[[ 2. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [ 0.  0. -1.  2.]]

Собственные числа вычисленные с помощью QR алгоритма:
[3.61803399 2.61803399 1.38196601 0.38196601]

Собственные числа вычисленные с помощью numpy:
[3.61803399 2.61803399 0.38196601 1.38196601]

Собственные векторы вычисленные с помощью QR алгоритма:
[[ 0.37174803 -0.60150096  0.60150096 -0.37174803]
 [ 0.60150096 -0.37174803 -0.37174803  0.60150096]
 [-0.60150096 -0.37174803  0.37174803  0.60150096]
 [ 0.37174803  0.60150096  0.60150096  0.37174803]]

Собственные векторы вычисленные с помощью numpy:
[[-0.37174803 -0.60150096 -0.37174803 -0.60150096]
 [ 0.60150096  0.37174803 -0.60150096 -0.37174803]
 [-0.60150096  0.37174803 -0.60150096  0.37174803]
 [ 0.37174803 -0.60150096 -0.37174803  0.60150096]]
